# Generated by Django 4.1.7 on 2023-02-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
